apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\domic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  containers:
    - name: backend
      image: domiciomedeiros/kanban-backend
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "1"
          memory: "524288e3"
        requests:
          cpu: 250m
          memory: "104857600"
      volumeMounts:
        - mountPath: /logs
          name: logs
      env:
        - name: JWT_SECRET
          value: password
        - name: POSTGRES_PWD
          value: password
    - name: filebeat
      image: domiciomedeiros/kanban-filebeat
      ports:
        - containerPort: 8085
      resources:
        limits:
          cpu: "1"
          memory: "524288e3"
        requests:
          cpu: 250m
          memory: "104857600"
      volumeMounts:
        - mountPath: /logs
          name: logs
          readOnly: true
  restartPolicy: OnFailure
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: logs
status: {}
