apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\domic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: backend
  type: NodePort
status:
  loadBalancer: {}
