version: '3.1'
services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "88:80"
  db:
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres
    build:
      dockerfile: Dockerfile
      context: ./postgres
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PWD=password
      - JWT_SECRET=password
    volumes:
      - logs:/logs:rw
      - type: bind
        source: ./logstash/certificates
        target: /certs
  client:
    build:
      context: ./client/Kanban
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend
    ports:
    - "3000:3000"
  filebeat:
    depends_on:
      - client
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./filebeat
    volumes:
      - logs:/logs:ro
      - type: bind
        source: ./logstash/certificates
        target: /certs
volumes:
  db-data:
  logs:
