version: '3.1'
services:
  db:
    image: 240238364947.dkr.ecr.us-east-1.amazonaws.com/kanban:db
    restart: always
    ports:
      - "5432:5432"
    build:
      dockerfile: Dockerfile
      context: ./postgres
  backend:
    image: 240238364947.dkr.ecr.us-east-1.amazonaws.com/kanban:backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PWD=password
      - JWT_SECRET=password