version: '3.1'
services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "88:80"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:kanban-nginx
  db:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:kanban-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres
    build:
      dockerfile: Dockerfile
      context: ./postgres
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PWD=password
      - JWT_SECRET=password
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:kanban-backend
  client:
    build:
      context: ./client/Kanban
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend
    ports:
    - "3000:3000"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:kanban-client
volumes:
  db-data:
