version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=password
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PWD=password
      - JWT_SECRET=password
volumes:
  db-data:
