version: '3.1'
services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "88:80"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PWD=password
      - JWT_SECRET=password
  client:
    build:
      context: ./client/Kanban
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend
    ports:
    - "3000:3000"
volumes:
  db-data:
