version: '3.1'
services:
  nginx:
    image: public.ecr.aws/u9g6t4t5/kanban:nginx
    depends_on:
      - client
      - backend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "0.5G"
        reservations:
          cpus: "0.25"
          memory: "0.1G"
  db:
    image: public.ecr.aws/u9g6t4t5/kanban:db
    restart: always
    ports:
      - "5432:5432"
    build:
      dockerfile: Dockerfile
      context: ./postgres
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "0.5G"
        reservations:
          cpus: "0.25"
          memory: "0.1G"
  backend:
    image: public.ecr.aws/u9g6t4t5/kanban:backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PWD=password
      - JWT_SECRET=password
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "0.5G"
        reservations:
          cpus: "0.25"
          memory: "0.1G"
  client:
    image: public.ecr.aws/u9g6t4t5/kanban:client
    build:
      context: ./client/Kanban
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend
    ports:
    - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "0.5G"
        reservations:
          cpus: "0.25"
          memory: "0.1G"
