apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\domic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\domic\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - image: domiciomedeiros/kanban-logstash
          name: logstash
          ports:
            - containerPort: 5044
          resources:
            limits:
              cpu: "1"
              memory: "700m"
            requests:
              cpu: 0.25
              memory: "500m"
      restartPolicy: Always
status: {}
