apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\domic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "88"
      port: 88
      targetPort: 80
  selector:
    io.kompose.service: nginx
  type: NodePort
status:
  loadBalancer: {}
