apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\domic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\domic\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: domiciomedeiros/kanban-nginx
          name: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "524288e3"
            requests:
              cpu: 250m
              memory: "104857600"
      restartPolicy: Always
status: {}
