apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\domic\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  containers:
    - image: domiciomedeiros/kanban-client
      name: client
      ports:
        - containerPort: 3000
      resources:
        limits:
          cpu: "1"
          memory: "524288e3"
        requests:
          cpu: 250m
          memory: "104857600"
  restartPolicy: OnFailure
status: {}
